### ISSUE TITLE
Checklist : Create public and private checklists

### ISSUE THREAD

**Issue by Djyp** [PointPlusYt/morgenbord-checklist-widget-bundle#2]

**Comment by Djyp** [comment]
Actually the feature for public checklists exists but there is no option about it.

- [ ] Add the option in the preferences
- [ ] Show the related button if the checklist can be public
- [ ] Add a voter on the public route
- [ ] Add an option to open the checklist to other users
